create table if not exists public.website_contact_submissions (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  company text not null,
  industry text not null,
  name text not null,
  email text not null,
  package text,
  message text not null,
  locale text not null default 'de' check (locale in ('de', 'en', 'fr', 'it')),
  source text not null default 'reward-me.ch'
);

alter table public.website_contact_submissions enable row level security;

-- No public policies are required. The Vercel function writes with the
-- server-only service role key; browsers never receive direct table access.
